# Generated by Django 4.0.4 on 2022-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
